function write_netlists(p, root)
%WRITE_NETLISTS Write every case in r1_cases as a SPICE netlist.
%   Netlists go under root/tina and are plain SPICE that TINA imports
%   (File > Import > SPICE netlist) and ngspice runs as is. Also writes
%   root/ngspice/run.sp, which runs them all and saves the results.

b = budgets(p);
i_lo = b.i_core - b.i_step;
cases = r1_cases(p);

for k = 1:numel(cases)
    c = cases(k);
    if strcmp(c.kind, 'ac')
        heading = '* R1 PDN impedance: 1 A AC into the die node, so V(die) reads in ohms';
        src = 'VVRM ref 0 DC 0 AC 0';
        drive = 'IAC 0 die DC 0 AC 1';
        analysis = {'.AC DEC 100 1k 1G'};
    else
        heading = sprintf('* R1 load step: %.0f A to %.0f A in %g ns', i_lo, b.i_core, c.rise_s * 1e9);
        src = sprintf('VVRM ref 0 DC %g', p.v_core);
        drive = sprintf('ILOAD die 0 PULSE(%g %g 20u %g %g 1m 2m)', i_lo, b.i_core, c.rise_s, c.rise_s);
        % GEAR integration: the micro-ohm, picohenry ladder is too stiff
        % for the default trapezoidal method.
        analysis = {'.OPTIONS METHOD=GEAR', '.TRAN 0.5n 60u 0 2n'};
    end
    file = fullfile(root, c.file);
    if ~exist(fileparts(file), 'dir')
        mkdir(fileparts(file));
    end
    fid = fopen(file, 'w');
    if fid < 0
        error('write_netlists:open', 'Cannot write %s', file);
    end
    fprintf(fid, '%s\n', heading);
    fprintf(fid, '* Generated by engineering/matlab/write_netlists.m from r1_params.m. Do not edit.\n');
    fprintf(fid, '* Package capacitors: %d top, %d land side\n', ...
        round(p.ptop.n * c.cap_scale), round(p.pland.n * c.cap_scale));
    fprintf(fid, '%s\n', src);
    fprintf(fid, 'RVRM ref vrm %g\n', p.vrm_r);
    fprintf(fid, 'LVRM vrm board %g\n', p.vrm_l);
    bank(fid, 'BULK', 'board', p.bulk, 1);
    bank(fid, 'BMLCC', 'board', p.bmlcc, 1);
    fprintf(fid, 'RBGA board bga %g\n', p.bga_r);
    fprintf(fid, 'LBGA bga pkg %g\n', p.bga_l);
    bank(fid, 'PTOP', 'pkg', p.ptop, c.cap_scale);
    bank(fid, 'PLAND', 'pkg', p.pland, c.cap_scale);
    fprintf(fid, 'RPKG pkg pkgl %g\n', p.pkg_r);
    fprintf(fid, 'LPKG pkgl die %g\n', p.pkg_l);
    fprintf(fid, 'RDIE die diec %g\n', p.die_esr);
    fprintf(fid, 'CDIE diec 0 %g\n', p.die_c);
    fprintf(fid, '%s\n', drive, analysis{:});
    fprintf(fid, '.END\n');
    fclose(fid);
end

% ngspice runner: the first line of a SPICE deck is always its title
fid = fopen(fullfile(root, 'ngspice', 'run.sp'), 'w');
fprintf(fid, '* Runs every TINA netlist in ngspice; results go to out/raw\n');
fprintf(fid, '* Generated by engineering/matlab/write_netlists.m. Run from engineering: ngspice -b ngspice/run.sp\n');
fprintf(fid, '.control\nset wr_singlescale\nset wr_vecnames\nshell mkdir -p out/raw\n');
for k = 1:numel(cases)
    v = 'v(die)';
    if strcmp(cases(k).kind, 'ac')
        v = 'vm(die)';
    end
    fprintf(fid, 'source %s\nrun\nwrdata out/raw/%s.txt %s\ndestroy all\n', cases(k).file, cases(k).name, v);
end
fprintf(fid, '.endc\n.end\n');
fclose(fid);
end

function bank(fid, name, node, c, scale)
% n identical capacitors lumped into one series R-L-C branch
n = round(c.n * scale);
if n == 0
    return
end
a = lower(name);
fprintf(fid, '* %s: %d x %g F, ESR %g ohm, ESL %g H\n', name, n, c.c, c.esr, c.esl);
fprintf(fid, 'R%s %s %s1 %g\n', name, node, a, c.esr / n);
fprintf(fid, 'L%s %s1 %s2 %g\n', name, a, a, c.esl / n);
fprintf(fid, 'C%s %s2 0 %g\n', name, a, c.c * n);
end
